# Generated by Django 5.1.4 on 2025-01-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_achievement_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_time_limit', models.PositiveIntegerField(default=30, help_text='Default time limit for quizzes in minutes')),
                ('points_per_question', models.PositiveIntegerField(default=1, help_text='Default points awarded per correct question')),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Show correct answers after quiz completion')),
                ('notify_new_quiz', models.BooleanField(default=False, help_text='Send notifications when new quizzes are available')),
                ('notify_results', models.BooleanField(default=True, help_text='Send quiz results via email')),
                ('enable_leaderboard', models.BooleanField(default=True, help_text='Enable the leaderboard feature')),
                ('minimum_pass_score', models.PositiveIntegerField(default=60, help_text='Minimum score required to pass a quiz (percentage)')),
                ('max_attempts_per_quiz', models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed per quiz')),
            ],
            options={
                'verbose_name': 'Quiz Settings',
                'verbose_name_plural': 'Quiz Settings',
            },
        ),
    ]
